#создание БД
version: '3'
services:
  db-cats-api:
    image: postgres:16-alpine
    restart: always
    container_name: db
    ports:
      - 5444:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: cats-api