server:
  # внешний порт приложения-контролера
  port: 8081

spring:
  application:
    name: cats-api
  datasource:
    # переменная DATASOURCE_HOST с ip БД, которая передается из командной строки или deployment.yaml
    url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:5444/cats-api
#    url: jdbc:postgresql://localhost:5444/cats-api
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

    jpa:
      database: postgresql
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          ddl-auto: none
